### ISSUE TITLE
Trial this config on Torchbox projects

### ISSUE THREAD

**Issue by thibaudcolas** [torchbox/eslint-config-torchbox#7]
It would be nice to set this up on a few key projects to see how the config fares, and backport any overrides into the config as needed. I’d rather not name specific projects here but let’s keep track of progress anyway:

- [x] Starter kit @thibaudcolas 
- [x] CRA project @thisoldbear 
- [ ] React project without CRA @kaedroho 
- [x] TypeScript project @kaedroho 
- [x] Not-React project started with starter kit @helenb
- [x] React project started with starter kit @thibaudcolas 
- [x] Not-React project

**Comment by helenb** [comment]
I trialled this on a build that is based on the starter kit, so much of the js comes from there. It is one where the tooling is still in the `static_src` directory, so my steps to get this set up were:

- Run npx install-peerdeps --dev eslint-config-torchbox inside the `static_src` directory
- Add `..eslintrc.js` to the `static_src` directory
- Remove the existing `.eslintrc` file from the `static_src` directory
- Run `npm run lint:js`.

There were quite a few issues that were raised by the new config.

**Good points that were raised**

- Lots of warnings to use `let` or `const` instead of `var`
- Suggestions to use `const` where variables are never reassigned
- Comment formatting (no space after `//`)
- This one I am not entirely sure I understand, but sounds like it would be good to fix:
`iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations` For this sort of line in the code:

```
for (const carousel of document.querySelectorAll(Carousel.selector())) {
        new Carousel(carousel);
}
```
- Noticed missing props validation for the test react component

**Warnings I think are not so useful**

- It complained about unnamed anonymous functions - why does that matter?
- It complained about string concatenation - I know it can be unclear, but sometimes you need it (relevant line of code below):

```
updateLiveRegion() {
        this.node.querySelector('.js-liveregion').textContent = 'Item ' + this.carousel.index + ' of ' + this.slideTotal;
    }
```

**Other points raised which I am not sure are useful or not and I don't fully understand**

- Expected an assignment or function call and instead saw an expression - from this line of code - I guess it wants a separate function

```
toggle() {
        this.toggledNode.classList.contains('is-open') ? this.close() : this.open();
}
```

- Must use destructuring state assignment (for the react component)
- Do not use 'new' for side effects

**Comment by thibaudcolas** [comment]
Thank you @helenb 👌 For the issues you mentioned:


## For-of

I would usually recommend converting the results from `querySelectorAll` to an array, then iterating through it with Array methods (`forEach`, `map`, `filter`, `some`, `every` etc). Using these leads to code that’s usually more concise (or at worst – same length), and conveys much more if using anything other than basic iteration.

## Unnamed anonymous functions

I don’t think it matters too much, but it’s good to be consistent with how we define functions (whatever pattern we use). Naming functions can improve error messages, but that’s not that true in modern JS engines.

## String concatenation

I would recommend always using template strings, so:

```js
elt.textContent = `Item ${this.carousel.index} of ${this.slideTotal}`;
```

There are two main advantages here – one is that you can then forget about the `+` sign being used for anything but numbers. The second is that this reduces the risk of bugs like: `this.carousel.index + this.slideTotal + ' items'`. While this might seem rare, it’s always worth being able to stop worry about a specific type of issues.

## Expression in toggle

This should be written with an `if-else` structure instead of abusing a ternary:

```js
toggle() {
    if (this.toggledNode.classList.contains('is-open')) {
        this.close();
    } else {
        this.open();
    }
}
```

## Destructuring state assignment

This is a convention for React components. Don’t feel so strongly about it either way.

## "new" for side effects

Here is what ESLint says about this: https://eslint.org/docs/rules/no-new

**Comment by thibaudcolas** [comment]
I’ll also copy @balazs-endresz’s feedback on using Airbnb’s config in place of CRA:

```
> no-semi
I used to prefer always using semicolons but it's actually quite nice without them. Btw, if we chose to use typescript that will also catch some (but not all) mistakes that can happen if you don't use semicolons. I don't mind either way.

If we don't want to use semis at all then (at least with typescript) the following seem to catch all semi-related mistakes I could think of (I tried this a while ago, airbnb might already cover these by default):
    "space-unary-ops": "warn",
    "no-unexpected-multiline": "error",
    "no-unreachable" : "error",
    "no-use-before-define": "warn",
    "func-call-spacing": ["warn", "never"]

> error  Line exceeds the maximum line length of 100       max-len
So airbnb uses 100 for the line length!


> error  Expected to return a value at the end of arrow function     consistent-return
> error  Unexpected block statement surrounding arrow body; move the returned value immediately after the `=>`  arrow-body-style
I don't really like these but there's a broader question of how many ways we should define functions.

> Assignment to property of function parameter 'state'  no-param-reassign
This might be nice to have in general, but it breaks RSK/immer reducers.

> 'react/jsx-indent': 4,
> 'react/jsx-indent-props': 4,
It doesn't take into account indent:4, so these have to be defined separately.


> error  'jest' is not defined          no-undef
> error  'document' is not defined        no-undef
These are fixable I assume.


> error  'promise' is never reassigned. Use 'const' instead      prefer-const
> error  JSX not allowed in files with extension '.js'             react/jsx-filename-extension
> error  propType "address" is not required, but has no corresponding defaultProps declaration   react/require-default-props
> error  'stats' is missing in props validation            react/prop-types
> error  ` Step        ` must be placed on a new line      react/jsx-one-expression-per-line
> error  'name' is already declared in the upper scope              no-shadow
> error  'activeFiltersIds' PropType is defined but prop is never used          react/no-unused-prop-types
> error  `classnames/bind` import should occur before import of `../Heading/Heading`                            import/order
> error  Expected 1 empty line after import statement not followed by another import       import/newline-after-import
> error  Unexpected parentheses around single function argument having a body with no curly braces              arrow-parens
> error  Do not access Object.prototype method 'hasOwnProperty' from target object        no-prototype-builtins
> error  Unary operator '++' used          no-plusplus
I like these 


> error  Expected property shorthand    object-shorthand
> error  '&&' should be placed at the beginning of the line   operator-linebreak
> error  Expected a line break after this opening brace        object-curly-newline
> error  Unexpected dangling '_' in '_data'       no-underscore-dangle
Don't seem too important but don't really mind these either
```

**Comment by thibaudcolas** [comment]
This is feeling pretty out of date so I’ll close this now. There are definite config changes we could do but it feels like they’d be more likely to get in if we treat them one-by-one as separate issues.
